### ISSUE TITLE
cannot build with python 3.2

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#70]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/61) by Anonymous.**

----------------------------------------

hg update -C version_2.2.x
python3 setup.py build

...

rpy/rinterface/rpy_device.c:1363: error: expected expression before ‘,’ token

...
