### ISSUE TITLE
Failed to compile with Python 3.6.0 on 32-bit Linux

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#403]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/389) by Felix Yan (Bitbucket: [felixonmars](https://bitbucket.org/felixonmars), GitHub: [felixonmars](https://github.com/felixonmars)).**

----------------------------------------

I am getting the following error when trying to compile rpy2 2.8.5 with Python 3.6.0 on i686:

```
In file included from ./rpy/rinterface/_rinterface.c:64:0:
/usr/include/R/Rinterface.h:106:24: error: conflicting types for 'uintptr_t'
  typedef unsigned long uintptr_t;
                        ^~~~~~~~~
In file included from /usr/lib/gcc/i686-pc-linux-gnu/6.2.1/include/stdint.h:9:0,
                 from /usr/include/inttypes.h:27,
                 from /usr/include/python3.6m/pyport.h:6,
                 from /usr/include/python3.6m/Python.h:50,
                 from ./rpy/rinterface/_rinterface.c:49:
/usr/include/stdint.h:128:23: note: previous declaration of 'uintptr_t' was here
 typedef unsigned int  uintptr_t;
                       ^~~~~~~~~
```
