### ISSUE TITLE
Doc:  The first piece of sample code in introduction.rst doesn't work with version 3.6.x

### ISSUE THREAD

**Issue by zftony** [rpy2/rpy2#1211]
**Describe the issue or bug**

In the Introduction, the following piece of code doesn't work  version 3.6.x.
```
import rpy2
print(rpy2.__version__)
```

**To Reproduce**

- Install any version >=3.6.0
- Run those two lines

**Expected behavior**
Doc needs to be updated.

**Error**
```
>>> import rpy2
>>> rpy2.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'rpy2' has no attribute '__version__'
```

**Additional context**
N/A
