### ISSUE TITLE
fatal error: 'R.h' file not found during build on OS X 10.9.2 using python 2.7.6

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#211]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/201) by Shantanu Joshi (Bitbucket: [shjoshi](https://bitbucket.org/shjoshi), GitHub: [shjoshi](https://github.com/shjoshi)).**

----------------------------------------

rpy2 fails to build on OS X 10.9 (Mavericks) via pip and easy_install.

The following error is produced:

In file included from ./rpy/rinterface/_rinterface.c:58:
./rpy/rinterface/_rinterface.h:8:10: fatal error: 'R.h' file not found
#include <R.h>
         ^
1 error generated.

The same error is produced even if I download source rpy2-2.4.0.tar.gz and do 
python setup.py install
